"""did some changes to db

Revision ID: 10e4447cb49e
Revises: 5f0b9bee1eaa
Create Date: 2025-11-01 16:04:38.082679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e4447cb49e'
down_revision: Union[str, Sequence[str], None] = '5f0b9bee1eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Permission', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('RefreshToken', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.add_column('RefreshToken', sa.Column('jti', sa.String(), nullable=False))
    op.alter_column('RefreshToken', 'hashed_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_RefreshToken_jti'), 'RefreshToken', ['jti'], unique=True)
    op.drop_column('User', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_RefreshToken_jti'), table_name='RefreshToken')
    op.alter_column('RefreshToken', 'hashed_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('RefreshToken', 'jti')
    op.drop_column('RefreshToken', 'is_revoked')
    op.alter_column('Permission', 'name',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
