"""added topic_id to Articles

Revision ID: 285e75808bc0
Revises: 8e32c2f2b0b9
Create Date: 2025-12-19 18:39:57.410389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285e75808bc0'
down_revision: Union[str, Sequence[str], None] = '8e32c2f2b0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Articles', 'Topic', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_Topic_id'), table_name='Topic')
    op.create_index(op.f('ix_Topic_id'), 'Topic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Topic_id'), table_name='Topic')
    op.create_index(op.f('ix_Topic_id'), 'Topic', ['id'], unique=True)
    op.drop_constraint(None, 'Articles', type_='foreignkey')
    op.drop_column('Articles', 'topic_id')
    # ### end Alembic commands ###
