"""sdfsd

Revision ID: 3187cd531b54
Revises: 403bd6553f03
Create Date: 2025-12-05 23:15:14.847099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3187cd531b54'
down_revision: Union[str, Sequence[str], None] = '403bd6553f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Articles', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('Articles', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Source', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Source', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('Articles', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Articles', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
