"""sdfsd

Revision ID: 330d1202a478
Revises: 3187cd531b54
Create Date: 2025-12-05 23:29:46.768213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330d1202a478'
down_revision: Union[str, Sequence[str], None] = '3187cd531b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Articles', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
