"""Some changes to articles

Revision ID: 5e0777d99320
Revises: 39e6919c8056
Create Date: 2025-11-21 04:14:00.457970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0777d99320'
down_revision: Union[str, Sequence[str], None] = '39e6919c8056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Articles_user_id_fkey'), 'Articles', type_='foreignkey')
    op.drop_column('Articles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('Articles_user_id_fkey'), 'Articles', 'User', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
