"""Create teble RefreshToken

Revision ID: 5f0b9bee1eaa
Revises: 64dbdcf44b91
Create Date: 2025-10-17 11:40:36.593024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0b9bee1eaa'
down_revision: Union[str, Sequence[str], None] = '64dbdcf44b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RefreshToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashed_token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RefreshToken_id'), 'RefreshToken', ['id'], unique=False)
    op.alter_column('Permission', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('Source', 'language',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('Topic', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Topic', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('Source', 'language',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('Permission', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_RefreshToken_id'), table_name='RefreshToken')
    op.drop_table('RefreshToken')
    # ### end Alembic commands ###
