"""migration to local database

Revision ID: 618f145ec0e4
Revises: 734a3c58d46d
Create Date: 2025-11-20 12:11:45.390672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618f145ec0e4'
down_revision: Union[str, Sequence[str], None] = '734a3c58d46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'RefreshToken', 'jti',
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        postgresql_using='jti::uuid',
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RefreshToken', 'jti',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
