"""sdfsd

Revision ID: 8e32c2f2b0b9
Revises: b367f4c1a195
Create Date: 2025-12-11 00:26:13.190923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e32c2f2b0b9'
down_revision: Union[str, Sequence[str], None] = 'b367f4c1a195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TestTable_id'), table_name='TestTable')
    op.drop_index(op.f('ix_TestTable_name'), table_name='TestTable')
    op.drop_table('TestTable')
    op.add_column('User', sa.Column('is_super', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_super')
    op.create_table('TestTable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('TestTable_pkey'))
    )
    op.create_index(op.f('ix_TestTable_name'), 'TestTable', ['name'], unique=False)
    op.create_index(op.f('ix_TestTable_id'), 'TestTable', ['id'], unique=False)
    # ### end Alembic commands ###
