"""test migration

Revision ID: a242240d4c22
Revises: 59920eb01a1f
Create Date: 2025-10-10 00:55:58.952517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a242240d4c22'
down_revision: Union[str, Sequence[str], None] = '59920eb01a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestTable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TestTable_id'), 'TestTable', ['id'], unique=False)
    op.create_index(op.f('ix_TestTable_name'), 'TestTable', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TestTable_name'), table_name='TestTable')
    op.drop_index(op.f('ix_TestTable_id'), table_name='TestTable')
    op.drop_table('TestTable')
    # ### end Alembic commands ###
