"""sdfsd

Revision ID: b367f4c1a195
Revises: 330d1202a478
Create Date: 2025-12-05 23:30:27.772060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b367f4c1a195'
down_revision: Union[str, Sequence[str], None] = '330d1202a478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Articles_content_hash'), table_name='Articles')
    op.drop_column('Articles', 'url')
    op.drop_column('Articles', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('Articles', sa.Column('url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_Articles_content_hash'), 'Articles', ['content_hash'], unique=True)
    # ### end Alembic commands ###
