""".

Revision ID: db90b01f6416
Revises: 285e75808bc0
Create Date: 2025-12-20 16:18:01.464083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db90b01f6416'
down_revision: Union[str, Sequence[str], None] = '285e75808bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_Articles_title'), 'Articles', ['title'], unique=False)
    op.create_unique_constraint(None, 'Articles', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Articles', type_='unique')
    op.drop_index(op.f('ix_Articles_title'), table_name='Articles')
    op.drop_column('Articles', 'url')
    # ### end Alembic commands ###
